### ISSUE TITLE
SCAD doesn't match Sainsmart Genmitsu 3030-Pro

### ISSUE THREAD

**Issue by gongloo** [heavior/parametric-spoilboard#1]
Looks like the SCAD as it's been uploaded doesn't match the Sainsmart Genmitsu 3030-Pro. The renders look about right (though I haven't confirmed exactly). Is it intentional that the specific coordinates for said machine are not in the source here? It'd be really great to include them in this repo for others to use/customize without having to go measure them out themselves!

**Comment by gongloo** [comment]
Ugh, sorry, I totally see this was user error now and didn't realize that twoPassMilling was enabled. Sorry for the spam!

**Comment by heavior** [comment]
Hey! Wow :) You are the fist person to use my repo. It's pretty cool, I'm glad you find it useful :) 

If you want to make a spoilboard - I'd recommend the Autodesk Fusion script from the repo, not SCAD, though
